Fix versioning race condition if others also update master directly
The race condition looks like
```
+ git push origin HEAD:master --follow-tags
warning: not sending a push certificate since the receiving end does not support --signed push
To ...
 * [new tag]         v1.4.23 -> v1.4.23
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://github.com/product-os/environment-production'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
and causes future versioning to fail because the tag already exists

Change-type: patch